[package]
name = "databricks_vectorsearch"
version = "0.1.0"
edition.workspace = true
license.workspace = true

[dependencies]
databricks_core = { path = "../core" }
serde.workspace = true
serde_json.workspace = true
tokio.workspace = true
